spring:

  application:
    name: spring-security-course

  data:
    web:
      pageable:
        size-parameter: limit
        page-parameter: p
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /api/v1
  port: 9191

security:
  default:
    role: CUSTOMER
  jwt:
    secret-key: bWkgY2xhdmUgZXMgbXV5IHNlZ3VyYSAxMjM0NTY3OCBhYmNkZWZn
    expiration-in-minutes: 30
