spring:

  application:
    name: spring-security-course

  data:
    web:
      pageable:
        size-parameter: limit
        page-parameter: p
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /api/v1

  port: 9191
